
export const passwordResetConfirmTypes = {
    PASSWORDRESETCONFIRM_REQUEST: "PASSWORDRESETCONFIRM_REQUEST",
    PASSWORDRESETCONFIRM_SUCCESS: "PASSWORDRESETCONFIRM_SUCCESS",
    PASSWORDRESETCONFIRM_FAILURE: "PASSWORDRESETCONFIRM_FAILURE"
 }